-- MySQL Script generated by MySQL Workbench
-- Mon Sep 20 15:18:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Marios_pizza
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Marios_pizza` ;

-- -----------------------------------------------------
-- Schema Marios_pizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Marios_pizza` DEFAULT CHARACTER SET utf8 ;
USE `Marios_pizza` ;

-- -----------------------------------------------------
-- Table `Marios_pizza`.`AddressInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`AddressInfo` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`AddressInfo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `HouseNumber` VARCHAR(10) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Zipcode` VARCHAR(6) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `AddressInfoID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Category` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Category` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Active` TINYINT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`City` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`City` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Municipality_ID` INT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `Municipality_ID`),
  INDEX `fk_City_Municipality1_idx` (`Municipality_ID` ASC) VISIBLE,
  CONSTRAINT `fk_City_Municipality1`
    FOREIGN KEY (`Municipality_ID`)
    REFERENCES `Marios_pizza`.`Municipality` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Coupon` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Coupon` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(45) NOT NULL,
  `DiscountPercentage` DECIMAL(7,3) NULL,
  `Discountprice` INT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Active` TINYINT NOT NULL,
  `StartDate` DATETIME NOT NULL,
  `EndDate` DATETIME NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Customer` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Customer` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Birthdate` DATE NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Phone1` VARCHAR(12) NOT NULL,
  `Phone2` VARCHAR(12) NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CustomerID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Customer_Addressinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Customer_Addressinfo` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Customer_Addressinfo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Customer_ID` INT NOT NULL,
  `AddressInfo_ID` INT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `Customer_ID`, `AddressInfo_ID`),
  INDEX `fk_Customer_Addressinfo_Customer1_idx` (`Customer_ID` ASC) VISIBLE,
  INDEX `fk_Customer_Addressinfo_AddressInfo1_idx` (`AddressInfo_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Addressinfo_Customer1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `Marios_pizza`.`Customer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_Addressinfo_AddressInfo1`
    FOREIGN KEY (`AddressInfo_ID`)
    REFERENCES `Marios_pizza`.`AddressInfo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`DeliveryType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`DeliveryType` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`DeliveryType` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NOT NULL,
  `Active` TINYINT NOT NULL DEFAULT 0,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`DifferentOpeningTime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`DifferentOpeningTime` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`DifferentOpeningTime` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Open` TIME NOT NULL,
  `Close` TIME NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NULL,
  `Shop_ID` INT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `Shop_ID`),
  INDEX `fk_DiffOpeningTime_Shop1_idx` (`Shop_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DiffOpeningTime_Shop1`
    FOREIGN KEY (`Shop_ID`)
    REFERENCES `Marios_pizza`.`Shop` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Ingredient` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Ingredient` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Active` TINYINT NOT NULL,
  `Tax_ID` INT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `Tax_ID`),
  INDEX `fk_Ingredients_Tax1_idx` (`Tax_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredients_Tax1`
    FOREIGN KEY (`Tax_ID`)
    REFERENCES `Marios_pizza`.`Tax` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Item_Property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Item_Property` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Item_Property` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PizzaBottom_ID` INT NULL,
  `Sauce_ID` INT NULL,
  `Ingredient_ID` INT NULL,
  `NonPizza_ID` INT NULL,
  `Property_ID` INT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `Property_ID`),
  INDEX `fk_Item_Property_PizzaBottom1_idx` (`PizzaBottom_ID` ASC) VISIBLE,
  INDEX `fk_Item_Property_Sauce1_idx` (`Sauce_ID` ASC) VISIBLE,
  INDEX `fk_Item_Property_Ingredient1_idx` (`Ingredient_ID` ASC) VISIBLE,
  INDEX `fk_Item_Property_Property1_idx` (`Property_ID` ASC) VISIBLE,
  INDEX `fk_Item_Property_NonPizza1_idx` (`NonPizza_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Property_PizzaBottom1`
    FOREIGN KEY (`PizzaBottom_ID`)
    REFERENCES `Marios_pizza`.`PizzaBottom` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Property_Sauce1`
    FOREIGN KEY (`Sauce_ID`)
    REFERENCES `Marios_pizza`.`Sauce` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Property_Ingredient1`
    FOREIGN KEY (`Ingredient_ID`)
    REFERENCES `Marios_pizza`.`Ingredient` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Property_Property1`
    FOREIGN KEY (`Property_ID`)
    REFERENCES `Marios_pizza`.`Property` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Property_NonPizza1`
    FOREIGN KEY (`NonPizza_ID`)
    REFERENCES `Marios_pizza`.`NonPizza` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Municipality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Municipality` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Municipality` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`NonPizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`NonPizza` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`NonPizza` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Active` TINYINT NOT NULL,
  `Tax_ID` INT NOT NULL,
  `SubCategory_ID` INT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `SubCategory_ID`, `Tax_ID`),
  INDEX `fk_NonPizza_Tax1_idx` (`Tax_ID` ASC) VISIBLE,
  INDEX `fk_NonPizza_SubCategory1_idx` (`SubCategory_ID` ASC) VISIBLE,
  CONSTRAINT `fk_NonPizza_Tax1`
    FOREIGN KEY (`Tax_ID`)
    REFERENCES `Marios_pizza`.`Tax` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NonPizza_SubCategory1`
    FOREIGN KEY (`SubCategory_ID`)
    REFERENCES `Marios_pizza`.`SubCategory` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`OpeningTime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`OpeningTime` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`OpeningTime` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NULL,
  `MonOpen` TIME NULL,
  `MonClosed` TIME NULL,
  `TueOpen` TIME NULL,
  `TueClosed` TIME NULL,
  `WedOpen` TIME NULL,
  `WedClosed` TIME NULL,
  `ThuOpen` TIME NULL,
  `ThueClosed` TIME NULL,
  `FriOpen` TIME NULL,
  `FriClosed` TIME NULL,
  `SatOpen` TIME NULL,
  `SatClosed` TIME NULL,
  `SunOpen` TIME NULL,
  `SunClosed` TIME NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Order` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Order` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `OrderStatus` TINYINT NOT NULL,
  `DeliveryPlan` DATETIME NOT NULL,
  `DeliveryTime` DATETIME NULL,
  `DeliveryPrice` DECIMAL(7,3) NOT NULL,
  `Customer_Id` INT NOT NULL,
  `DeliveryType_ID` INT NOT NULL,
  `Shop_ID` INT NOT NULL,
  `OrderDate` TIMESTAMP NOT NULL,
  `TotalOrderPrice` DECIMAL(7,3) NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_Order_Customer_idx` (`Customer_Id` ASC) VISIBLE,
  INDEX `fk_Order_DeliveryType1_idx` (`DeliveryType_ID` ASC) VISIBLE,
  PRIMARY KEY (`ID`, `Customer_Id`, `DeliveryType_ID`, `Shop_ID`),
  INDEX `fk_Order_Shop1_idx` (`Shop_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer`
    FOREIGN KEY (`Customer_Id`)
    REFERENCES `Marios_pizza`.`Customer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_DeliveryType`
    FOREIGN KEY (`DeliveryType_ID`)
    REFERENCES `Marios_pizza`.`DeliveryType` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Shop`
    FOREIGN KEY (`Shop_ID`)
    REFERENCES `Marios_pizza`.`Shop` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`OrderItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`OrderItem` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`OrderItem` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `OrderID` INT NOT NULL,
  `Pizza_ID` INT NULL,
  `NonPizza_ID` INT NULL,
  `OrderName` VARCHAR(45) NOT NULL,
  `Amount` INT NOT NULL,
  `TotalPrice` DECIMAL(7,3) NOT NULL,
  `Tax` DECIMAL(7,3) NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_Order_id` (`OrderID` ASC) INVISIBLE,
  PRIMARY KEY (`ID`, `OrderID`),
  INDEX `fk_OrderItem_NonPizza1_idx` (`NonPizza_ID` ASC) VISIBLE,
  INDEX `fk_OrderItem_Pizza1_idx` (`Pizza_ID` ASC) VISIBLE,
  CONSTRAINT `fk_OrderItem_NonPizza1`
    FOREIGN KEY (`NonPizza_ID`)
    REFERENCES `Marios_pizza`.`NonPizza` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_Order1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `Marios_pizza`.`Order` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_Pizza1`
    FOREIGN KEY (`Pizza_ID`)
    REFERENCES `Marios_pizza`.`Pizza` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 16;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Order_Coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Order_Coupon` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Order_Coupon` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Order_ID` INT NOT NULL,
  `Coupon_ID` INT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `Coupon_ID`),
  INDEX `fk_Order_Coupon_Coupon1_idx` (`Coupon_ID` ASC) VISIBLE,
  INDEX `fk_Order_Coupon_Order1_idx` (`Order_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Coupon_Coupon1`
    FOREIGN KEY (`Coupon_ID`)
    REFERENCES `Marios_pizza`.`Coupon` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Coupon_Order1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `Marios_pizza`.`Order` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Pizza` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Pizza` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Sauce_ID` INT NOT NULL,
  `PizzaBottom_ID` INT NOT NULL,
  `IsCustom` TINYINT NOT NULL DEFAULT 0 COMMENT 'Standaard GEEN custom pizza',
  `SubCategory_ID` INT NOT NULL,
  `Active` TINYINT NOT NULL DEFAULT 0,
  `Description` VARCHAR(255) NOT NULL,
  `Price` DECIMAL(4,3) NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `Sauce_ID`, `PizzaBottom_ID`, `SubCategory_ID`),
  INDEX `fk_Pizza_Sauce1_idx` (`Sauce_ID` ASC) VISIBLE,
  INDEX `fk_Pizza_PizzaBottom1_idx` (`PizzaBottom_ID` ASC) VISIBLE,
  INDEX `fk_Pizza_SubCategory1_idx` (`SubCategory_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pizza_Sauce1`
    FOREIGN KEY (`Sauce_ID`)
    REFERENCES `Marios_pizza`.`Sauce` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_PizzaBottom1`
    FOREIGN KEY (`PizzaBottom_ID`)
    REFERENCES `Marios_pizza`.`PizzaBottom` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_SubCategory1`
    FOREIGN KEY (`SubCategory_ID`)
    REFERENCES `Marios_pizza`.`SubCategory` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`PizzaBottom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`PizzaBottom` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`PizzaBottom` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Size` VARCHAR(45) NOT NULL,
  `Active` TINYINT NOT NULL,
  `Tax_ID` INT NOT NULL,
  `PizzaBottomType_ID` INT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `PizzaBottomType_ID`, `Tax_ID`),
  INDEX `fk_PizzaBottom_Tax1_idx` (`Tax_ID` ASC) VISIBLE,
  INDEX `fk_PizzaBottom_PizzaBottomType1_idx` (`PizzaBottomType_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PizzaBottom_Tax1`
    FOREIGN KEY (`Tax_ID`)
    REFERENCES `Marios_pizza`.`Tax` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PizzaBottom_PizzaBottomType1`
    FOREIGN KEY (`PizzaBottomType_ID`)
    REFERENCES `Marios_pizza`.`PizzaBottomType` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`PizzaBottomType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`PizzaBottomType` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`PizzaBottomType` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(255) NULL,
  `Active` TINYINT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Pizza_Ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Pizza_Ingredient` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Pizza_Ingredient` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Pizza_ID` INT NOT NULL,
  `Ingredient_ID` INT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `Pizza_ID`, `Ingredient_ID`),
  INDEX `fk_Pizza_Ingredient_Ingredient1_idx` (`Ingredient_ID` ASC) VISIBLE,
  INDEX `fk_Pizza_Ingredient_Pizza1_idx` (`Pizza_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pizza_Ingredient_Ingredient1`
    FOREIGN KEY (`Ingredient_ID`)
    REFERENCES `Marios_pizza`.`Ingredient` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_Ingredient_Pizza1`
    FOREIGN KEY (`Pizza_ID`)
    REFERENCES `Marios_pizza`.`Pizza` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Property` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Property` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(255) NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Sauce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Sauce` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Sauce` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Tax_ID` INT NOT NULL,
  `Active` TINYINT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `Tax_ID`),
  INDEX `fk_Sauce_Tax1_idx` (`Tax_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Sauce_Tax1`
    FOREIGN KEY (`Tax_ID`)
    REFERENCES `Marios_pizza`.`Tax` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`ServiceArea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`ServiceArea` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`ServiceArea` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Zipcode` VARCHAR(6) NOT NULL,
  `BreakpointStart` VARCHAR(6) NOT NULL,
  `BreakpointEnd` VARCHAR(6) NOT NULL,
  `Street_ID` INT NOT NULL,
  `Shop_ID` INT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `Street_ID`),
  INDEX `fk_ZipCode_Shop1_idx` (`Shop_ID` ASC) VISIBLE,
  INDEX `fk_ZipCode_StreetName1_idx` (`Street_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ZipCode_Shop1`
    FOREIGN KEY (`Shop_ID`)
    REFERENCES `Marios_pizza`.`Shop` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZipCode_StreetName1`
    FOREIGN KEY (`Street_ID`)
    REFERENCES `Marios_pizza`.`Street` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Shop` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Shop` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(75) NOT NULL,
  `Phone` VARCHAR(12) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `StreetName` VARCHAR(75) NOT NULL,
  `HouseNumber` VARCHAR(10) NOT NULL,
  `Zipcode` VARCHAR(6) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  `OpeningTime_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Shop_OpeningTime1_idx` (`OpeningTime_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Shop_OpeningTime1`
    FOREIGN KEY (`OpeningTime_ID`)
    REFERENCES `Marios_pizza`.`OpeningTime` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Street`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Street` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Street` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(75) NOT NULL,
  `City_ID` INT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `City_ID`),
  INDEX `fk_StreetName_City1_idx` (`City_ID` ASC) VISIBLE,
  CONSTRAINT `fk_StreetName_City1`
    FOREIGN KEY (`City_ID`)
    REFERENCES `Marios_pizza`.`City` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`SubCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`SubCategory` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`SubCategory` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Active` TINYINT NOT NULL DEFAULT 0,
  `Categorie_ID` INT NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`, `Categorie_ID`),
  INDEX `fk_SubCategory_Category1_idx` (`Categorie_ID` ASC) VISIBLE,
  CONSTRAINT `fk_SubCategory_Category1`
    FOREIGN KEY (`Categorie_ID`)
    REFERENCES `Marios_pizza`.`Category` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marios_pizza`.`Tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Marios_pizza`.`Tax` ;

CREATE TABLE IF NOT EXISTS `Marios_pizza`.`Tax` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tax` DECIMAL(7,3) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `CreatedOn` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(45) NOT NULL,
  `LastUpdate` DATETIME NOT NULL,
  `UpdateBy` VARCHAR(45) NOT NULL,
  `Deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

USE `Marios_pizza`;

DELIMITER $$

USE `Marios_pizza`$$
DROP TRIGGER IF EXISTS `Marios_pizza`.`Pizza_Ingredient_BEFORE_INSERT` $$
USE `Marios_pizza`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Marios_pizza`.`Pizza_Ingredient_BEFORE_INSERT` BEFORE INSERT ON `Pizza_Ingredient` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
